### ISSUE TITLE
Error on blender 2.91

### ISSUE THREAD

**Issue by tlf30** [Mwni/blender-animation-retargeting#12]
Hello,
I am getting an error on blender 2.91:
```
Python: Traceback (most recent call last):
  File "C:\Users\Trevor\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-animation-retargeting-master\alignment.py", line 136, in execute
    leave_edit()
  File "C:\Users\Trevor\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-animation-retargeting-master\alignment.py", line 75, in leave_edit
    s.update_drivers()
  File "C:\Users\Trevor\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-animation-retargeting-master\addon.py", line 219, in update_drivers
    drivers.build()
  File "C:\Users\Trevor\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-animation-retargeting-master\drivers.py", line 153, in build
    clear()
  File "C:\Users\Trevor\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender-animation-retargeting-master\drivers.py", line 116, in clear
    dest_pose.driver_remove('location')
AttributeError: 'NoneType' object has no attribute 'driver_remove'

location: <unknown location>:-1
```

**Comment by tlf30** [comment]
I'm getting the same error on Blender 2.83.

**Comment by Mwni** [comment]
At which step did this occur?

**Comment by tlf30** [comment]
The error occurs at ever step after selecting the source and destination. The first appearance of the error is when adding the bone map, and it will occur every step following, including baking and attempting to remove the bone map. Baking does not work. I tested several models, but all FBX exported from the same tool. A friend of mine using one of the same models on blender 2.91 does not get this error.  I have tried importing a working bone map, and building a new one.

**Comment by Mwni** [comment]
I tested the addon on 2.92 and got no errors either. I'm going to need a copy of your armature to test it out myself.

**Comment by tlf30** [comment]
@Mwni I think I have finally figured out what I was doing wrong. In my tests I hade accidently deleted some of the leaf bones on the target. I am going to assume the error was that it was unable to find the bone, which consequently means I cannot remove mapping to that bone.

**Comment by Mwni** [comment]
The bones you deleted were mapped beforehand? If so, yes that would definitely throw an exception. Thanks for reporting. Will add to to-do list.

**Comment by tlf30** [comment]
Yep, that is exactly what I did wrong. Thank you
