### ISSUE TITLE
Hard lock during mapping

### ISSUE THREAD

**Issue by BlackShift** [Mwni/blender-animation-retargeting#37]
I can't seem to figure out why, but the add-on hard locks on specific armature with the following error:

```
Python: Traceback (most recent call last):
  File "C:\Users\Deploy\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-animation-retargeting-stable\main.py", line 39, in draw
    mapping.draw_panel(ctx, layout.box())
  File "C:\Users\Deploy\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-animation-retargeting-stable\mapping.py", line 36, in draw_panel
    bones_n = len(ctx.get_guessing_bones())
  File "C:\Users\Deploy\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-animation-retargeting-stable\context.py", line 132, in get_guessing_bones
    return [bone for bone in bpy.context.selected_pose_bones if bone.name in self.target.pose.bones]
TypeError: 'NoneType' object is not iterable
```

It seems the addon will get into an invalid state and I can't seem to recover it.

**Comment by Mwni** [comment]
Neither `bpy.context.selected_pose_bones` nor `self.target.pose.bones` should be None. Is source or target hidden or unlinked perhaps?

**Comment by BlackShift** [comment]
I had some bones hidden, then this came up, I tried un-hiding them, but the issue still persists.

**Comment by Mwni** [comment]
Without knowing your setup, I cannot help further

**Comment by BlackShift** [comment]
Is there a way to clear what ever object data or cache that exists? The issue persists across saves. Or is there is no persistent data store?

**Comment by BlackShift** [comment]
Solved, by going into the context and unchecking ui_guessing_mappings and others
![image](https://github.com/user-attachments/assets/465600f0-db8f-40a3-bfce-cd27d2ba52ae)
