### ISSUE TITLE
Baking - Error 'nonetype' object has no attribute 'action'

### ISSUE THREAD

**Issue by ImagePlant** [Mwni/blender-animation-retargeting#40]
First off, great addon!

And it works until the very last step of baking....

Mocap data (403 frames) and an imported bvh in rest pose (403 frames)

Retargeted mocap data to bvh - success and aside from 2 mapping tweaks (left and right shoulders) nothing else needed.

Attempted "Bake into Action":

Error result:
![image](https://github.com/user-attachments/assets/a96d1f48-21db-4931-a40f-b7f68dadf2c8)

**Comment by Mwni** [comment]
The error message implies that your source armature has no "animation action" set. Is that possible?

**Comment by ImagePlant** [comment]
Ok thanks.  Luckily this doesn't affect my bvh export.  I wasn't sure if I needed to bake before export or not but it doesn't seem necessary if I understand correctly?

**Comment by Mwni** [comment]
I don't understand the question.

**Comment by ImagePlant** [comment]
I looked at the action editor and it's populated.  It exports ok (without using the bake function).  But why use the bake function?  If I use the bake function, the error I mentioned earlier occurs.

![image](https://github.com/user-attachments/assets/74b02291-6779-4dea-b1fd-2d5951a9bc20)

**Comment by Mwni** [comment]
Yes, this is a bug. Would you be willing to share your .blend file or another minimal repro?

**Comment by slippystance** [comment]
[recording_12_47_16_gmt-7-REMAPPING_v03.zip](https://github.com/user-attachments/files/17498510/recording_12_47_16_gmt-7-REMAPPING_v03.zip)

Attached here.

**Comment by milanwulf** [comment]
I have a similar error when I try to bake something. My source armature has several action clips in the NLE, could this be problematic?

`Python: Traceback (most recent call last):
  File "C:\Users\unframe03\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-animation-retargeting-stable\baking.py", line 93, in execute
    transfer_anim(ctx)
  File "C:\Users\unframe03\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\blender-animation-retargeting-stable\baking.py", line 43, in transfer_anim
    target_action_name = ctx.target.name + '|' + source_action.name.replace(ctx.source.name + '|', '')
                                                 ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
`

**Comment by Mwni** [comment]
@milanwulf Did you stash the action? Try selecting the source armature, then going into the Action Editor and picking an action from the dropdown.

**Comment by milanwulf** [comment]
@Mwni thanks for the quick reply, I realized this a few minutes later, it was my mistake. The batch import feature is very handy, but I think it would also be nice to be able to bake multiple animations from the source armature (NLE action strips) to the target armature. Anyway, it's a very nice tool, you should consider adding it to the new Blender Extensions page (https://extensions.blender.org/).

**Comment by 123ysys** [comment]
> [@Mwni](https://github.com/Mwni) thanks for the quick reply, I realized this a few minutes later, it was my mistake. The batch import feature is very handy, but I think it would also be nice to be able to bake multiple animations from the source armature (NLE action strips) to the target armature. Anyway, it's a very nice tool, you should consider adding it to the new Blender Extensions page (https://extensions.blender.org/).

Hello. What is the reason of this problem? And how did you resolve it? I am also facing this problem, and hope you can tell me the way to resolve. Thank you.

**Comment by 123ysys** [comment]
> > [@Mwni](https://github.com/Mwni) thanks for the quick reply, I realized this a few minutes later, it was my mistake. The batch import feature is very handy, but I think it would also be nice to be able to bake multiple animations from the source armature (NLE action strips) to the target armature. Anyway, it's a very nice tool, you should consider adding it to the new Blender Extensions page (https://extensions.blender.org/).
> 
> Hello. What is the reason of this problem? And how did you resolve it? I am also facing this problem, and hope you can tell me the way to resolve. Thank you.

@milanwulf

**Comment by Joseffb** [comment]
I had these problems AFTER I would do one successful import. All subsequent wold have these types of issues. 

I solved it by deleting the old action fbx, then also going to the objects and deleting residual fbx object that blender didn't delete for me. Once all traces of the old source model was gone it worked.

This addon gave a lot more cusotmization then the Rokomo plugin and once you know how to reset it worked great. 

I wish the bulk import actually worked as it seemed to overwrite them all unto same action channel (doesnt fake user them between actions).

Also understand I'm new to blender so novice issues persisted.
